import _ from 'lodash';


var people = [{
    "id": 1,
    "first_name": "Grata",
    "last_name": "Luttgert",
    "email": "gluttgert0@goo.ne.jp",
    "gender": "Female",
    "ip_address": "76.87.174.214"
  }, {
    "id": 2,
    "first_name": "Way",
    "last_name": "Croneen",
    "email": "wcroneen1@deviantart.com",
    "gender": "Male",
    "ip_address": "201.43.111.81"
  }, {
    "id": 3,
    "first_name": "D'arcy",
    "last_name": "Erricker",
    "email": "derricker2@indiatimes.com",
    "gender": "Male",
    "ip_address": "71.248.46.172"
  }, {
    "id": 4,
    "first_name": "Gibb",
    "last_name": "Loveredge",
    "email": "gloveredge3@umich.edu",
    "gender": "Male",
    "ip_address": "101.4.231.120"
  }, {
    "id": 5,
    "first_name": "Lynett",
    "last_name": "Kennham",
    "email": "lkennham4@dmoz.org",
    "gender": "Female",
    "ip_address": "150.75.22.249"
  }, {
    "id": 6,
    "first_name": "Jonell",
    "last_name": "Lacroux",
    "email": "jlacroux5@cargocollective.com",
    "gender": "Female",
    "ip_address": "227.249.212.49"
  }, {
    "id": 7,
    "first_name": "Ave",
    "last_name": "Trenholm",
    "email": "atrenholm6@g.co",
    "gender": "Male",
    "ip_address": "44.194.69.36"
  }, {
    "id": 8,
    "first_name": "Jonis",
    "last_name": "Stranks",
    "email": "jstranks7@reverbnation.com",
    "gender": "Female",
    "ip_address": "211.30.71.105"
  }, {
    "id": 9,
    "first_name": "Davina",
    "last_name": "Hallsworth",
    "email": "dhallsworth8@phpbb.com",
    "gender": "Female",
    "ip_address": "251.53.180.74"
  }, {
    "id": 10,
    "first_name": "Shae",
    "last_name": "Trenouth",
    "email": "strenouth9@amazon.co.uk",
    "gender": "Male",
    "ip_address": "95.188.216.226"
  }, {
    "id": 11,
    "first_name": "Alexandr",
    "last_name": "Armes",
    "email": "aarmesa@cdbaby.com",
    "gender": "Male",
    "ip_address": "7.212.41.137"
  }, {
    "id": 12,
    "first_name": "Bili",
    "last_name": "Elgie",
    "email": "belgieb@shareasale.com",
    "gender": "Female",
    "ip_address": "21.236.142.4"
  }, {
    "id": 13,
    "first_name": "Nanete",
    "last_name": "Ackenson",
    "email": "nackensonc@digg.com",
    "gender": "Female",
    "ip_address": "168.172.133.248"
  }, {
    "id": 14,
    "first_name": "Colan",
    "last_name": "Isson",
    "email": "cissond@comcast.net",
    "gender": "Male",
    "ip_address": "40.229.102.16"
  }, {
    "id": 15,
    "first_name": "Sherwin",
    "last_name": "Purnell",
    "email": "spurnelle@tinyurl.com",
    "gender": "Male",
    "ip_address": "186.169.232.176"
  }, {
    "id": 16,
    "first_name": "Martica",
    "last_name": "Birchwood",
    "email": "mbirchwoodf@vistaprint.com",
    "gender": "Female",
    "ip_address": "107.184.165.222"
  }, {
    "id": 17,
    "first_name": "Ingrid",
    "last_name": "Primmer",
    "email": "iprimmerg@buzzfeed.com",
    "gender": "Female",
    "ip_address": "128.112.165.97"
  }, {
    "id": 18,
    "first_name": "Cyrus",
    "last_name": "Ciccoloi",
    "email": "cciccoloih@goo.gl",
    "gender": "Male",
    "ip_address": "119.149.45.161"
  }, {
    "id": 19,
    "first_name": "Silvester",
    "last_name": "Tinkham",
    "email": "stinkhami@seattletimes.com",
    "gender": "Male",
    "ip_address": "117.123.186.14"
  }, {
    "id": 20,
    "first_name": "Ciro",
    "last_name": "Wimbush",
    "email": "cwimbushj@netscape.com",
    "gender": "Male",
    "ip_address": "112.236.6.101"
  }]


var MaleCount = _.filter(people, {gender: 'Male'}).length;
alert(MaleCount + ' Male People');
  